# Generated by Django 3.2.5 on 2021-08-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=300)),
                ('paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.BooleanField(default=True, help_text='Показать на главной странице что товар новый', verbose_name='Новый товар')),
                ('top', models.BooleanField(default=False, help_text='Показать на главной странице', verbose_name='Топ товар')),
                ('family', models.CharField(choices=[('m', 'Мужчинам'), ('w', 'Женщинам'), ('k', 'Детям'), ('o', 'Выберите пол')], default='o', max_length=10)),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_main', models.ImageField(upload_to='media/products/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('sizes', models.TextField(blank=True)),
                ('one_size', models.BooleanField(default=False)),
                ('S', models.BooleanField(default=False)),
                ('M', models.BooleanField(default=False)),
                ('L', models.BooleanField(default=False)),
                ('XL', models.BooleanField(default=False)),
                ('XXL', models.BooleanField(default=False)),
                ('XXXL', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default='Без категории', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Товар', to='ShopApp.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
                'index_together': {('id', 'slug', 'top', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Slaider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='media/slaidbar/%Y/%m/%d')),
                ('title', models.CharField(max_length=20)),
                ('sub_title', models.CharField(max_length=40)),
                ('button_title', models.CharField(max_length=15)),
                ('button_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.tovar')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ShopApp.order', verbose_name='Товар')),
                ('product', models.ForeignKey(db_tablespace=1, on_delete=django.db.models.deletion.CASCADE, related_name='Товар', to='ShopApp.tovar', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
