# Generated by Django 3.2.5 on 2021-07-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='top',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterIndexTogether(
            name='tovar',
            index_together={('id', 'slug', 'top', 'category')},
        ),
    ]
