# Generated by Django 3.2.5 on 2021-08-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slaider',
        ),
    ]
