# Generated by Django 3.2.5 on 2021-08-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_delete_slaider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slaider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='media/slaidbar/%Y/%m/%d')),
                ('title', models.CharField(max_length=20)),
                ('sub_title', models.CharField(max_length=40)),
                ('button_title', models.CharField(max_length=15)),
                ('button_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.tovar')),
            ],
        ),
    ]
