# Generated by Django 3.2.5 on 2021-07-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0003_alter_tovar_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='top',
            field=models.BooleanField(default=False, help_text='Показать на главной странице', verbose_name='Топ товар'),
        ),
    ]
