# Generated by Django 3.2.5 on 2021-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0004_alter_tovar_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='image_main',
            field=models.ImageField(upload_to='media/products/%Y/%m/%d'),
        ),
    ]
