# Generated by Django 3.2.5 on 2021-07-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0005_alter_tovar_image_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='category',
            field=models.ForeignKey(default='Без категории', on_delete=django.db.models.deletion.CASCADE, related_name='Товар', to='ShopApp.category'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
