# Generated by Django 3.2.5 on 2021-07-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0006_auto_20210726_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='name',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
