# Generated by Django 3.2.5 on 2021-07-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0007_alter_tovar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='sizes',
            field=models.TextField(blank=True),
        ),
    ]
