# Generated by Django 3.2.5 on 2021-08-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0007_alter_tovar_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='kod',
            field=models.CharField(default='28', max_length=6),
        ),
    ]
