# Generated by Django 3.2.5 on 2021-07-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0008_tovar_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('surname', models.CharField(db_index=True, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=40)),
                ('adress', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Товар', to='ShopApp.tovar')),
            ],
        ),
    ]
