# Generated by Django 3.2.5 on 2021-08-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0009_alter_tovar_kod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='stock',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(db_tablespace=1, default=1, on_delete=django.db.models.deletion.CASCADE, to='ShopApp.tovar', verbose_name='Товары'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tovar',
            name='sale',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город/обл'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Коментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оформление заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='category',
            field=models.ForeignKey(default='Без категории', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Товар', to='ShopApp.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='family',
            field=models.CharField(choices=[('o', 'Выберите пол'), ('m', 'Мужчинам'), ('w', 'Женщинам'), ('k', 'Детям')], default='o', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='image1',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Дополнительное фото'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Дополнительное фото'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='image3',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Дополнительное фото'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='image4',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Дополнительное фото'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='image_main',
            field=models.ImageField(upload_to='media/products/%Y/%m/%d', verbose_name='Главное фото*'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='kod',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='Сылка на товар'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
    ]
