# Generated by Django 3.2.5 on 2021-07-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0009_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('name',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='orders',
            name='adress2',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
