# Generated by Django 3.2.5 on 2021-07-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0010_auto_20210726_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='tovar',
        ),
    ]
