# Generated by Django 3.2.5 on 2021-08-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0012_auto_20210822_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='comment',
            new_name='message',
        ),
    ]
