# Generated by Django 3.2.5 on 2021-07-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0013_auto_20210727_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
