# Generated by Django 3.2.5 on 2021-07-29 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0015_auto_20210729_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaider',
            name='background',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/slaidbar/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
