# Generated by Django 3.2.5 on 2021-08-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0020_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
