# Generated by Django 3.2.5 on 2021-08-15 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0024_auto_20210815_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ShopApp.category', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Товар', to='ShopApp.sub_category'),
        ),
    ]
