# Generated by Django 3.2.5 on 2021-08-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0026_auto_20210815_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='category',
            field=models.ForeignKey(default='Без категории', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Товар', to='ShopApp.category'),
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
