# Generated by Django 3.2.5 on 2021-08-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0027_auto_20210816_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='family',
            field=models.CharField(choices=[('man', 'Мужчинам'), ('women', 'Женщинам'), ('kids', 'Детям'), ('other', 'Выберите пол')], default='other', max_length=10),
        ),
    ]
