# Generated by Django 3.2.5 on 2021-08-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0028_tovar_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='family',
            field=models.CharField(choices=[('m', 'Мужчинам'), ('w', 'Женщинам'), ('k', 'Детям'), ('o', 'Выберите пол')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='new',
            field=models.BooleanField(default=True, help_text='Показать на главной странице что товар новый', verbose_name='Новый товар'),
        ),
    ]
