# Generated by Django 3.2.5 on 2021-08-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0029_auto_20210816_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='family',
            field=models.CharField(choices=[('m', 'Мужчинам'), ('w', 'Женщинам'), ('k', 'Детям'), ('o', 'Выберите пол')], default='o', max_length=10),
        ),
    ]
